sonar_oculus:
  ros__parameters:

    model: "M3000d"

    frame_id: "sonar"

    # Frequency mode: 
    #   1 = LowFrequency  (M750d: 750kHz, M1200d: 1.2Mhz, M3000d: 1.2Mhz)
    #   2 = HighFrequency (M750d: 1.2Mhz, M1200d: 2.1Mhz, M3000d:   3Mhz)
    Mode: 1

    # Ping rate:
    #   0 = Normal (10Hz max)
    #   1 = High (15Hz max)
    #   2 = Highest (40Hz max)
    #   3 = Low (5Hz max)
    #   4 = Lowest (2Hz max)
    PingRate: 3

    # Gain in percentage (0–100)
    Gain: 20

    # Range in meters (1–120)
    Range: 10

    # Salinity in ppm (0–50)
    Salinity: 0

    # Colormap for oculus_viewer:
    #   0=Autumn, 1=Bone, 2=Cool, 3=Hot, 4=HSV,
    #   5=Jet, 6=Ocean, 7=Pink, 8=Rainbow, 
    #   9=Spring, 10=Summer, 11=Winter
    Colormap: 1

    # Raw image flag
    Raw: false